### ISSUE TITLE
.promiseToSink -> .sink, .promiseToThrough -> .through

### ISSUE THREAD

**Issue by ahdinosaur** [queckezz/pull-promise#1]
heyo @queckezz, cool module.

as some minor feedback, you might want to follow the API of other `pull-stream` modules that are similar, namely using `.sink()` instead of `.promiseToSink()` and `.through()` instead of `.promiseToThrough()`.

examples using this API: [`pull-defer`](https://github.com/pull-stream/pull-defer), [`stream-to-pull-stream`](https://github.com/pull-stream/stream-to-pull-stream).

of course, like totes up to you, just thought i'd share. :smile:

**Comment by queckezz** [comment]
Thanks for the input! Changed. Also:
- swapped to just using es5 since that seems to be the default
- separated into files, `require('pull-promise/through')`, `require('pull-promise/source')`
